apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: j26-strapi-kv-csi
spec:
  provider: azure
  secretObjects:
  - secretName: j26-strapi-secrets
    type: Opaque
    data:
    - key: APP_KEYS
      objectName: j26-strapi-app-keys
    - key: API_TOKEN_SALT
      objectName: j26-strapi-api-token-salt
    - key: ADMIN_JWT_SECRET
      objectName: j26-strapi-admin-jwt-secret
    - key: TRANSFER_TOKEN_SALT
      objectName: j26-strapi-transfer-token-salt
    - key: ENCRYPTION_KEY
      objectName: j26-strapi-encryption-key
    - key: JWT_SECRET
      objectName: j26-strapi-jwt-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 214abfc2-fa80-44b9-89c5-f78444a16816
    keyvaultName: kv-j26apps-shared-sdc
    tenantId: 317a47ba-fd32-41b8-8ebe-310a1adc9863
    objects: |
      array:
        - |
          objectName: j26-strapi-app-keys
          objectType: secret
        - |
          objectName: j26-strapi-api-token-salt
          objectType: secret
        - |
          objectName: j26-strapi-admin-jwt-secret
          objectType: secret
        - |
          objectName: j26-strapi-transfer-token-salt
          objectType: secret
        - |
          objectName: j26-strapi-encryption-key
          objectType: secret
        - |
          objectName: j26-strapi-jwt-secret
          objectType: secret
