apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: j26-scoutin-2-kv-csi
spec:
  provider: azure
  secretObjects:
  - secretName: j26-scoutin-2-secrets
    type: Opaque
    data:
    - key: ADMIN_PASSWORD
      objectName: j26-scoutin-2-admin-password
    - key: TOKEN_SECRET
      objectName: j26-scoutin-2-token-secret
    - key: DATASOURCE_HASHING_SECRET
      objectName: j26-scoutin-2-datasource-hashing-secret
    - key: DATASOURCE_HASHING_SALT
      objectName: j26-scoutin-2-datasource-hashing-salt
    - key: BLOCKLIST_HASHING_SECRET
      objectName: j26-scoutin-2-blocklist-hashing-secret
    - key: SCOUTNET_GROUPS_GROUPS_KEY
      objectName: j26-scoutin-2-scoutnet-groups-groups-key
    - key: SCOUTNET_GROUPS_PARTICIPANTS_KEY
      objectName: j26-scoutin-2-scoutnet-groups-participants-key
    - key: SCOUTNET_GROUPS_CHECKIN_KEY
      objectName: j26-scoutin-2-scoutnet-groups-checkin-key
    - key: SCOUTNET_GROUPS_QUESTIONS_KEY
      objectName: j26-scoutin-2-scoutnet-groups-questions-key
    - key: SCOUTNET_STAFF_GROUPS_KEY
      objectName: j26-scoutin-2-scoutnet-staff-groups-key
    - key: SCOUTNET_STAFF_PARTICIPANTS_KEY
      objectName: j26-scoutin-2-scoutnet-staff-participants-key
    - key: SCOUTNET_STAFF_CHECKIN_KEY
      objectName: j26-scoutin-2-scoutnet-staff-checkin-key
    - key: SCOUTNET_STAFF_QUESTIONS_KEY
      objectName: j26-scoutin-2-scoutnet-staff-questions-key
    - key: GOOGLE_SA_KEY
      objectName: j26-scoutin-2-google-sa-key
    - key: SCOUTNET_STORMOTE6_ORDINARY_GROUPS_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-groups-key
    - key: SCOUTNET_STORMOTE6_ORDINARY_PARTICIPANTS_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-participants-key
    - key: SCOUTNET_STORMOTE6_ORDINARY_CHECKIN_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-checkin-key
    - key: SCOUTNET_STORMOTE6_ORDINARY_QUESTIONS_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-questions-key
    - key: SCOUTNET_STORMOTE6_LATE_GROUPS_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-late-groups-key
    - key: SCOUTNET_STORMOTE6_LATE_PARTICIPANTS_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-late-participants-key
    - key: SCOUTNET_STORMOTE6_LATE_CHECKIN_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-late-checkin-key
    - key: SCOUTNET_STORMOTE6_LATE_QUESTIONS_KEY
      objectName: j26-scoutin-2-scoutnet-stormote6-late-questions-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 214abfc2-fa80-44b9-89c5-f78444a16816
    keyvaultName: kv-j26apps-shared-sdc
    tenantId: 317a47ba-fd32-41b8-8ebe-310a1adc9863
    objects: |
      array:
        - |
          objectName: j26-scoutin-2-admin-password
          objectType: secret
        - |
          objectName: j26-scoutin-2-token-secret
          objectType: secret
        - |
          objectName: j26-scoutin-2-datasource-hashing-secret
          objectType: secret
        - |
          objectName: j26-scoutin-2-datasource-hashing-salt
          objectType: secret
        - |
          objectName: j26-scoutin-2-blocklist-hashing-secret
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-groups-groups-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-groups-participants-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-groups-checkin-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-groups-questions-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-staff-groups-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-staff-participants-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-staff-checkin-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-staff-questions-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-google-sa-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-groups-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-participants-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-checkin-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-ordinary-questions-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-late-groups-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-late-participants-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-late-checkin-key
          objectType: secret
        - |
          objectName: j26-scoutin-2-scoutnet-stormote6-late-questions-key
          objectType: secret
