apiVersion: v1
kind: ConfigMap
metadata:
  name: j26-scoutid-sync-participants-config
data:
  KEYCLOAK_BASE_URL: https://admin.id.dev.j26.se
  KEYCLOAK_REALM_NAME: jamboree26
  KEYCLOAK_CLIENT_ID: j26-group-import
  KEYCLOAK_PARENT_GROUP_ID: c89151a0-078e-4922-b6f3-8526e301a3e2
  SCOUTNET_PROJECT_ID: "52710"
  SCOUTNET_FORM_ID: "43844"
  WRITE_CONCURRENCY: "5"
  MAX_RETRIES: "7"
