apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-keyvault-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Scouterna/j26-infra.git
    targetRevision: HEAD
    path: k8s/manifests/azure-keyvault-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
